name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag "4architmehta/newsflash:${{ steps.vars.outputs.sha_short }}" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "4architmehta/newsflash:${{ steps.vars.outputs.sha_short }}"

      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/NewsFlash
            sudo docker compose -p newsflash down
            sudo docker stop newsflash-web-1
            sudo docker rm newsflash-web-1
            sudo docker rmi newsflash-web
            sudo docker compose -p newsflash up --build -d
            yes | sudo docker container prune
            yes | sudo docker system prune
