name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag "4architmehta/newsflash:${{ steps.vars.outputs.sha_short }}" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "4architmehta/newsflash:${{ steps.vars.outputs.sha_short }}"

      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            export NEWS_TAG=${{ steps.vars.outputs.sha_short }}
            sudo docker stop newsflash-backend
            sudo docker rm newsflash-backend
            sudo docker rmi $(sudo docker images -q 4architmehta/newsflash)
            sudo docker pull "4architmehta/newsflash:${NEWS_TAG}"
            sudo docker run -dp 5000:8000 --name newsflash-backend "4architmehta/newsflash:${NEWS_TAG}"
            yes | sudo docker container prune
